
POST http://localhost:3333/books
Content-Type: application/json

{
    "title": "Novo livro",
    "author": "John doe",
    "isbnNumber": 77777
}

###
PUT http://localhost:3333/books/645d263e0731d96430fa082e
Content-Type: application/json

{
    "title": "Livro teste",
    "author": "Teste",
    "isbnNumber": 12345566
}